"""add embedding vector to chunks

Revision ID: 90f25312c764
Revises: b2d572c8c13e
Create Date: 2026-05-29 23:02:21.815479

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90f25312c764"
down_revision: Union[str, None] = "b2d572c8c13e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('chunks', 'embedding',
    #            existing_type=sa.VARCHAR(),
    #            type_=VECTOR(dim=384),
    #            nullable=True)
    # op.drop_index('idx_chunks_document_id', table_name='chunks')
    # op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    # # ### end Alembic commands ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute("""
        ALTER TABLE chunks
        ALTER COLUMN embedding
        TYPE vector(384)
        USING NULL
    """)

    op.drop_index("idx_chunks_document_id", table_name="chunks")
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"], unique=False)


def downgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_chunks_document_id', table_name='chunks')
    # op.create_index('idx_chunks_document_id', 'chunks', ['document_id'], unique=False)
    # op.alter_column('chunks', 'embedding',
    #            existing_type=VECTOR(dim=384),
    #            type_=sa.VARCHAR(),
    #            nullable=False)
    # # ### end Alembic commands ###
    op.drop_index("ix_chunks_document_id", table_name="chunks")

    op.create_index("idx_chunks_document_id", "chunks", ["document_id"], unique=False)

    op.execute("""
        ALTER TABLE chunks
        ALTER COLUMN embedding
        TYPE VARCHAR
    """)
