"""add refresh tokens

Revision ID: b8d2f6e07158
Revises: 90f25312c764
Create Date: 2026-06-10 00:37:24.056970

"""

from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8d2f6e07158"
down_revision: Union[str, None] = "90f25312c764"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("chunks", "embedding", existing_type=VECTOR(dim=384), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks", "embedding", existing_type=VECTOR(dim=384), nullable=False
    )
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
